import Collections
import VProxyCommon

let ETHER_TYPE_8021Q: UInt16 = 0x8100
let ETHER_TYPE_ARP: UInt16 = 0x0806
let ETHER_TYPE_IPv4: UInt16 = 0x0800
let ETHER_TYPE_IPv6: UInt16 = 0x86DD

let BE_ETHER_TYPE_8021Q = Convert.reverseByteOrder(ETHER_TYPE_8021Q)
let BE_ETHER_TYPE_ARP = Convert.reverseByteOrder(ETHER_TYPE_ARP)
let BE_ETHER_TYPE_IPv4 = Convert.reverseByteOrder(ETHER_TYPE_IPv4)
let BE_ETHER_TYPE_IPv6 = Convert.reverseByteOrder(ETHER_TYPE_IPv6)

let ARP_PROTOCOL_TYPE_IP: UInt16 = 0x0800
let ARP_HARDWARE_TYPE_ETHER: UInt16 = 1
let ARP_PROTOCOL_OPCODE_REQ: UInt16 = 1
let ARP_PROTOCOL_OPCODE_RESP: UInt16 = 2

let BE_ARP_PROTOCOL_TYPE_IP = Convert.reverseByteOrder(ARP_PROTOCOL_TYPE_IP)
let BE_ARP_HARDWARE_TYPE_ETHER = Convert.reverseByteOrder(ARP_HARDWARE_TYPE_ETHER)
let BE_ARP_PROTOCOL_OPCODE_REQ = Convert.reverseByteOrder(ARP_PROTOCOL_OPCODE_REQ)
let BE_ARP_PROTOCOL_OPCODE_RESP = Convert.reverseByteOrder(ARP_PROTOCOL_OPCODE_RESP)

let IP_PROTOCOL_ICMP: UInt8 = 1
let IP_PROTOCOL_ICMPv6: UInt8 = 58
let IP_PROTOCOL_TCP: UInt8 = 6
let IP_PROTOCOL_UDP: UInt8 = 17

let IPv6_needs_next_header: Set<UInt8> = [0, 60, 43, 44, 51, 50, 135, 139, 140, 253, 254]

let ICMP_PROTOCOL_TYPE_ECHO_REQ: UInt8 = 8
let ICMPv6_PROTOCOL_TYPE_ECHO_REQ: UInt8 = 128
let ICMP_PROTOCOL_TYPE_ECHO_RESP: UInt8 = 0
let ICMPv6_PROTOCOL_TYPE_ECHO_RESP: UInt8 = 129
let ICMP_PROTOCOL_TYPE_TIME_EXCEEDED: UInt8 = 11
let ICMPv6_PROTOCOL_TYPE_TIME_EXCEEDED: UInt8 = 3
let ICMPv6_PROTOCOL_TYPE_Neighbor_Solicitation: UInt8 = 135
let ICMPv6_PROTOCOL_TYPE_Neighbor_Advertisement: UInt8 = 136
let ICMPv6_OPTION_TYPE_Source_Link_Layer_Address: UInt8 = 1
let ICMPv6_OPTION_TYPE_Target_Link_Layer_Address: UInt8 = 2
let ICMP_PROTOCOL_TYPE_DEST_UNREACHABLE: UInt8 = 3
let ICMP_PROTOCOL_CODE_PORT_UNREACHABLE: UInt8 = 3
let ICMPv6_PROTOCOL_TYPE_DEST_UNREACHABLE: UInt8 = 1
let ICMPv6_PROTOCOL_CODE_PORT_UNREACHABLE: UInt8 = 4

public nonisolated(unsafe) let IPv6_LINK_LOCAL_ADDRS = NetworkV6(from: "fe80::/10")!
